### ISSUE TITLE
cant run with optifabric 1.13.25

### ISSUE THREAD

**Issue by zyzkun** [enjarai/do-a-barrel-roll#100]
heres crash reports

Mod resolution encountered an incompatible mod set!
- A potential solution has been determined:
  - Replace mod 'Do a Barrel Roll' (do_a_barrel_roll) 3.2.0+1.20 with any version that is compatible with:
    optifabric 1.13.25
Unmet dependency listing:
 - <html>Mod 'Do a Barrel Roll' (do_a_barrel_roll) 3.2.0+1.20 is incompatible with any version of mod 'OptiFabric' (optifabric),<br>but 
 a matching version is present: 1.13.25!</html>

**Comment by zyzkun** [comment]
WARNING: Unknown module: cpw.mods.bootstraplauncher specified to --add-exports
jlw: native file exists: 'C:\Users\Ethan\AppData\Roaming\PCL\libjlw-1.3.2.dll'.
jlw: native file checked.
[22:27:55] [main/INFO]: Loading Minecraft 1.20.1 with Fabric Loader 0.14.22
[22:27:55] [ForkJoinPool-1-worker-20/WARN]: Mod wurst uses the version v7.35.2-MC1.20 which isn't compatible with Loader's extended semantic version format (Could not parse version number component 'v7'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[22:27:55] [main/WARN]: Mod resolution failed
[22:27:55] [main/INFO]: Immediate reason: [NEG_HARD_DEP do_a_barrel_roll 3.2.0+1.20 {breaks optifabric @ [*]}, ROOT_FORCELOAD_SINGLE do_a_barrel_roll 3.2.0+1.20, ROOT_FORCELOAD_SINGLE optifabric 1.13.25]
[22:27:55] [main/INFO]: Reason: [NEG_HARD_DEP do_a_barrel_roll 3.2.0+1.20 {breaks optifabric @ [*]}]
[22:27:55] [main/INFO]: Fix: add [], remove [], replace [[do_a_barrel_roll 3.2.0+1.20] -> add:do_a_barrel_roll 1 ([(-鈭?鈭?])]
[22:27:55] [main/ERROR]: Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'Do a Barrel Roll' (do_a_barrel_roll) 3.2.0+1.20 with any version that is compatible with:
		 - optifabric 1.13.25
Unmet dependency listing:
	 - Mod 'Do a Barrel Roll' (do_a_barrel_roll) 3.2.0+1.20 is incompatible with any version of mod 'OptiFabric' (optifabric), but a matching version is present: 1.13.25!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:192) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.22.jar:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:577) ~[?:?]
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:60) ~[?:?]
	at oolloo.jlw.Wrapper.main(Wrapper.java:53) ~[?:?]

**Comment by enjarai** [comment]
Optifine breaks this mod in a multitude of ways that I can't track down, and you probably shouldn't be using it on modern versions of Minecraft. I'd recommend removing Optifine and switching to alternatives outlined here:

https://lambdaurora.dev/optifine_alternatives/

**Comment by zyzkun** [comment]
yes i use 1.17.1 to play this
in fact its not as fun as i thought)
