### ISSUE TITLE
When used with "Icarus" mod by Cammie, if you go in water while flying on a server, it crashes your game and you have to delete your character file to play again

### ISSUE THREAD

**Issue by AmazingGates96** [enjarai/do-a-barrel-roll#139]
I'm using the Prominence II modpack and have these two mods together, every time on my family server that someone enters the water (it seems to be only while flying, and only with the Icarus wings) they crash and the only way to play on the server again is if they delete their character file completely from the server PC. I don't have the crash log right now because my brother is the one who kept having this happen to him, and it's a pain to get everything back. If need be I can try to replicate it, but it's very annoying to deal with afterward and I'd like to avoid that until it's necessary. Seems to only happen in multiplayer, unsure if this applies to LAN at the moment.

**Comment by enjarai** [comment]
Hmm thats a strange one for sure. I'd definitely need a crash log to diagnose this im afraid. You might be able to use a dummy server to reproduce the issue?

**Comment by AmazingGates96** [comment]
It works for the LAN servers now with the updated version of Icarus!! I'll try the regular server later once my dad updates the modpack on the server computer, but it should be working now!

**Comment by enjarai** [comment]
Given the lack of follow up, I'll assume this issue is fixed. Feel free to reopen if it appears again!

**Comment by Alone2War** [comment]
I have encountered the same issue, here is the server side error that is given when the kick occurs. Hope this helps.

[20:38:51] [Server thread/WARN]: Error loading class: dev/cammiescorner/icarus/client/IcarusClient (java.lang.RuntimeException: Cannot load class dev.cammiescorner.icarus.client.IcarusClient in environment type SERVER)
[20:38:51] [Server thread/WARN]: Neruina Caught Exception
net.minecraft.class_148: Ticking player
        at net.minecraft.class_3222.method_14226(class_3222.java:574) ~[server-intermediary.jar:?]
        at net.minecraft.class_3244.mixinextras$bridge$method_14226$175(class_3244.java) ~[server-intermediary.jar:?]
        at com.bawnorton.neruina.handler.NeruinaTickHandler.safelyTickPlayer$notTheCauseOfTickLag(NeruinaTickHandler.java:63) ~[neruina-1.3.0-fabric+1.18.2-1.20.1.jar:?]
        at net.minecraft.class_3244.wrapOperation$fil000$neruina$catchTickingPlayer(class_3244.java:9954) ~[server-intermediary.jar:?]
        at net.minecraft.class_3244.method_18784(class_3244.java:269) ~[server-intermediary.jar:?]
        at net.minecraft.class_2535.method_10754(class_2535.java:259) ~[server-intermediary.jar:?]
        at net.minecraft.class_3242.method_14357(class_3242.java:172) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:908) ~[server-intermediary.jar:?]
        at net.minecraft.class_3176.method_3813(class_3176.java:283) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.RuntimeException: Mixin transformation of dev.cammiescorner.icarus.core.util.IcarusHelper failed
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427) ~[fabric-loader-0.14.25.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.25.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.25.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.14.25.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        at dev.cammiescorner.icarus.common.items.WingItem.tick(WingItem.java:54) ~[icarus-1.16.jar:?]
        at net.minecraft.class_1661.mde060f6$trinkets$lambda$updateItems$0$6(class_1661.java:7693) ~[server-intermediary.jar:?]
        at dev.emi.trinkets.api.LivingEntityTrinketComponent.forEach(LivingEntityTrinketComponent.java:362) ~[trinkets-3.7.1.jar:?]
        at net.minecraft.class_1661.mde060f6$trinkets$lambda$updateItems$1$5(class_1661.java:7692) ~[server-intermediary.jar:?]
        at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
        at net.minecraft.class_1661.handler$ine001$trinkets$updateItems(class_1661.java:7691) ~[server-intermediary.jar:?]
        at net.minecraft.class_1661.method_7381(class_1661.java:260) ~[server-intermediary.jar:?]
        at net.minecraft.class_1657.method_6007(class_1657.java:568) ~[server-intermediary.jar:?]
        at net.minecraft.class_1309.method_5773(class_1309.java:2419) ~[server-intermediary.jar:?]
        at net.minecraft.class_1657.method_5773(class_1657.java:283) ~[server-intermediary.jar:?]
        at net.minecraft.class_3222.method_14226(class_3222.java:510) ~[server-intermediary.jar:?]
        ... 12 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.14.25.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.25.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.25.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.14.25.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        at dev.cammiescorner.icarus.common.items.WingItem.tick(WingItem.java:54) ~[icarus-1.16.jar:?]
        at net.minecraft.class_1661.mde060f6$trinkets$lambda$updateItems$0$6(class_1661.java:7693) ~[server-intermediary.jar:?]
        at dev.emi.trinkets.api.LivingEntityTrinketComponent.forEach(LivingEntityTrinketComponent.java:362) ~[trinkets-3.7.1.jar:?]
        at net.minecraft.class_1661.mde060f6$trinkets$lambda$updateItems$1$5(class_1661.java:7692) ~[server-intermediary.jar:?]
        at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
        at net.minecraft.class_1661.handler$ine001$trinkets$updateItems(class_1661.java:7691) ~[server-intermediary.jar:?]
        at net.minecraft.class_1661.method_7381(class_1661.java:260) ~[server-intermediary.jar:?]
        at net.minecraft.class_1657.method_6007(class_1657.java:568) ~[server-intermediary.jar:?]
        at net.minecraft.class_1309.method_5773(class_1309.java:2419) ~[server-intermediary.jar:?]
        at net.minecraft.class_1657.method_5773(class_1657.java:283) ~[server-intermediary.jar:?]
        at net.minecraft.class_3222.method_14226(class_3222.java:510) ~[server-intermediary.jar:?]
        ... 12 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinPreProcessorException: Attach error for medievalorigins.mixins.json:IcarusHelperMixin from mod medievalorigins during activity: [Transform -> Method modifyArmorModifier(FLnet/minecraft/class_1657;Lnet/minecraft/class_1799;)F -> GETSTATIC -> dev/cammiescorner/icarus/client/IcarusClient::armourSlows:Z]
        at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:313) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:277) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1289) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:294) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.14.25.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.25.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.25.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.14.25.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        at dev.cammiescorner.icarus.common.items.WingItem.tick(WingItem.java:54) ~[icarus-1.16.jar:?]
        at net.minecraft.class_1661.mde060f6$trinkets$lambda$updateItems$0$6(class_1661.java:7693) ~[server-intermediary.jar:?]
        at dev.emi.trinkets.api.LivingEntityTrinketComponent.forEach(LivingEntityTrinketComponent.java:362) ~[trinkets-3.7.1.jar:?]
        at net.minecraft.class_1661.mde060f6$trinkets$lambda$updateItems$1$5(class_1661.java:7692) ~[server-intermediary.jar:?]
        at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
        at net.minecraft.class_1661.handler$ine001$trinkets$updateItems(class_1661.java:7691) ~[server-intermediary.jar:?]
        at net.minecraft.class_1661.method_7381(class_1661.java:260) ~[server-intermediary.jar:?]
        at net.minecraft.class_1657.method_6007(class_1657.java:568) ~[server-intermediary.jar:?]
        at net.minecraft.class_1309.method_5773(class_1309.java:2419) ~[server-intermediary.jar:?]
        at net.minecraft.class_1657.method_5773(class_1657.java:283) ~[server-intermediary.jar:?]
        at net.minecraft.class_3222.method_14226(class_3222.java:510) ~[server-intermediary.jar:?]
        ... 12 more
Caused by: java.lang.RuntimeException: java.lang.ClassNotFoundException: dev.cammiescorner.icarus.client.IcarusClient
        at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transformMemberReference(MixinPreProcessorStandard.java:786) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transformField(MixinPreProcessorStandard.java:777) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transform(MixinPreProcessorStandard.java:740) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:307) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:277) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1289) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:294) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.14.25.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.25.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.25.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.14.25.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        at dev.cammiescorner.icarus.common.items.WingItem.tick(WingItem.java:54) ~[icarus-1.16.jar:?]
        at net.minecraft.class_1661.mde060f6$trinkets$lambda$updateItems$0$6(class_1661.java:7693) ~[server-intermediary.jar:?]
        at dev.emi.trinkets.api.LivingEntityTrinketComponent.forEach(LivingEntityTrinketComponent.java:362) ~[trinkets-3.7.1.jar:?]
        at net.minecraft.class_1661.mde060f6$trinkets$lambda$updateItems$1$5(class_1661.java:7692) ~[server-intermediary.jar:?]
        at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
        at net.minecraft.class_1661.handler$ine001$trinkets$updateItems(class_1661.java:7691) ~[server-intermediary.jar:?]
        at net.minecraft.class_1661.method_7381(class_1661.java:260) ~[server-intermediary.jar:?]
        at net.minecraft.class_1657.method_6007(class_1657.java:568) ~[server-intermediary.jar:?]
        at net.minecraft.class_1309.method_5773(class_1309.java:2419) ~[server-intermediary.jar:?]
        at net.minecraft.class_1657.method_5773(class_1657.java:283) ~[server-intermediary.jar:?]
        at net.minecraft.class_3222.method_14226(class_3222.java:510) ~[server-intermediary.jar:?]
        ... 12 more
Caused by: java.lang.ClassNotFoundException: dev.cammiescorner.icarus.client.IcarusClient
        at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transformMemberReference(MixinPreProcessorStandard.java:786) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transformField(MixinPreProcessorStandard.java:777) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transform(MixinPreProcessorStandard.java:740) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:307) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:277) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1289) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:294) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.14.25.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.25.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.25.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.14.25.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        at dev.cammiescorner.icarus.common.items.WingItem.tick(WingItem.java:54) ~[icarus-1.16.jar:?]
        at net.minecraft.class_1661.mde060f6$trinkets$lambda$updateItems$0$6(class_1661.java:7693) ~[server-intermediary.jar:?]
        at dev.emi.trinkets.api.LivingEntityTrinketComponent.forEach(LivingEntityTrinketComponent.java:362) ~[trinkets-3.7.1.jar:?]
        at net.minecraft.class_1661.mde060f6$trinkets$lambda$updateItems$1$5(class_1661.java:7692) ~[server-intermediary.jar:?]
        at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
        at net.minecraft.class_1661.handler$ine001$trinkets$updateItems(class_1661.java:7691) ~[server-intermediary.jar:?]
        at net.minecraft.class_1661.method_7381(class_1661.java:260) ~[server-intermediary.jar:?]
        at net.minecraft.class_1657.method_6007(class_1657.java:568) ~[server-intermediary.jar:?]
        at net.minecraft.class_1309.method_5773(class_1309.java:2419) ~[server-intermediary.jar:?]
        at net.minecraft.class_1657.method_5773(class_1657.java:283) ~[server-intermediary.jar:?]
        at net.minecraft.class_3222.method_14226(class_3222.java:510) ~[server-intermediary.jar:?]
        ... 12 more
[20:38:51] [Server thread/INFO]: Alone2War lost connection: You have been kicked due to a ticking exception on your player. Please remove the culprit mod or contact an admin.
[20:38:51] [Server thread/INFO]: Alone2War left the game

**Comment by enjarai** [comment]
This looks to me like it's an incompatibility between medieval origins and icarus, the former failing to do something with the latter. Do a Barrel Roll is not involved from what I can tell, you'll probably want to report this to medieval origins.
