### ISSUE TITLE
Minecraft crash when open a singleplayer and multiplayer worlds.

### ISSUE THREAD

**Issue by MasterYTGamingTR** [enjarai/do-a-barrel-roll#181]
# Issue
I tried opening a singleplayer world and it crash the game. (Same with multiplayer)

# Crash report/logs
---- Minecraft Crash Report ----
// Shall we play a game?

Time: 2024-12-07 15:03:48
Description: Unexpected error

java.lang.NullPointerException: Cannot invoke "nl.enjarai.doabarrelroll.api.RollEntity.doABarrelRoll$isRolling()" because "focusedEntity" is null
	at knot//net.minecraft.class_4184.handler$zco000$do_a_barrel_roll$doABarrelRoll$captureTickDeltaAndUpdate(class_4184.java:562)
	at knot//net.minecraft.class_4184.method_19321(class_4184.java)
	at knot//net.minecraft.class_757.method_3188(class_757.java:1052)
	at knot//net.minecraft.class_757.method_3192(class_757.java:850)
	at knot//net.minecraft.class_310.method_1523(class_310.java:1285)
	at knot//net.minecraft.class_310.method_1514(class_310.java:882)
	at knot//fudge.notenoughcrashes.mixinhandlers.InGameCatcher.handleClientCrash(InGameCatcher.java:37)
	at knot//net.minecraft.class_310.modify$bjh000$notenoughcrashes$atTheEndOfSecondCatchBeforePrintingCrashReport(class_310.java:10755)
	at knot//net.minecraft.class_310.method_1514(class_310.java:905)
	at knot//net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.21.1
	Minecraft Version ID: 1.21.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 21.0.2, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 426419552 bytes (406 MiB) / 1073741824 bytes (1024 MiB) up to 3154116608 bytes (3008 MiB)
	CPUs: 4
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-4200H CPU @ 2.80GHz
	Identifier: Intel64 Family 6 Model 60 Stepping 3
	Microarchitecture: Haswell (Client)
	Frequency (GHz): 2.79
	Number of physical packages: 1
	Number of physical CPUs: 2
	Number of logical CPUs: 4
	Graphics card #0 name: NVIDIA GeForce GTX 850M
	Graphics card #0 vendor: NVIDIA
	Graphics card #0 VRAM (MiB): 2048.00
	Graphics card #0 deviceId: VideoController1
	Graphics card #0 versionInfo: 32.0.15.5599
	Graphics card #1 name: Intel(R) HD Graphics 4600
	Graphics card #1 vendor: Intel Corporation
	Graphics card #1 VRAM (MiB): 1024.00
	Graphics card #1 deviceId: VideoController2
	Graphics card #1 versionInfo: 20.19.15.4531
	Memory slot #0 capacity (MiB): 4096.00
	Memory slot #0 clockSpeed (GHz): 1.60
	Memory slot #0 type: DDR3
	Memory slot #1 capacity (MiB): 4096.00
	Memory slot #1 clockSpeed (GHz): 1.60
	Memory slot #1 type: DDR3
	Virtual memory max (MiB): 12939.03
	Virtual memory used (MiB): 10054.58
	Swap memory total (MiB): 4864.00
	Swap memory used (MiB): 250.83
	Space in storage for jna.tmpdir (MiB): available: 382777.00, total: 476312.13
	Space in storage for org.lwjgl.system.SharedLibraryExtractPath (MiB): available: 382777.00, total: 476312.13
	Space in storage for io.netty.native.workdir (MiB): available: 382777.00, total: 476312.13
	Space in storage for java.io.tmpdir (MiB): available: 382777.00, total: 476312.13
	Space in storage for workdir (MiB): available: 382777.00, total: 476312.13
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx3000M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		betterf3: BetterF3 11.0.2
			cloth-config: Cloth Config v15 15.0.127
				cloth-basic-math: cloth-basic-math 0.6.1
		betterstats: Better Statistics Screen 3.13.3+fabric-1.21
		boatcam: BoatCam 1.0.3
		cherishedworlds: Cherished Worlds 10.1.0+1.21.1
		cicada: CICADA 0.9.1+1.21-1.21.1
		citresewn: CIT Resewn 1.2.2+1.21
			citresewn-defaults: CIT Resewn: Defaults 1.2.2+1.21
		clumps: Clumps 19.0.0.1
		do_a_barrel_roll: Do a Barrel Roll 3.7.2
			fabric-permissions-api-v0: fabric-permissions-api 0.2-SNAPSHOT
			mixinsquared: MixinSquared 0.1.2-beta.4
		eatinganimationid: Eating Animation 1.21+1.9.72
		entityculling: EntityCulling 1.7.0
		fabric-api: Fabric API 0.110.0+1.21.1
			fabric-api-base: Fabric API Base 0.4.42+6573ed8c19
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.70+b559734419
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.30+be1ed2d719
			fabric-block-api-v1: Fabric Block API (v1) 1.0.22+0af3f5a719
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.10+6573ed8c19
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.52+0af3f5a719
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.15+6573ed8c19
			fabric-command-api-v1: Fabric Command API (v1) 1.2.49+f71b366f19
			fabric-command-api-v2: Fabric Command API (v2) 2.2.28+6ced4dd919
			fabric-commands-v0: Fabric Commands (v0) 0.2.66+df3654b319
			fabric-content-registries-v0: Fabric Content Registries (v0) 8.0.18+b559734419
			fabric-convention-tags-v1: Fabric Convention Tags 2.1.2+7f945d5b19
			fabric-convention-tags-v2: Fabric Convention Tags (v2) 2.9.2+e60e56d419
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.29+0af3f5a719
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.4.0+da19b51a19
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 20.2.24+16c4ae2519
			fabric-dimensions-v1: Fabric Dimensions API (v1) 4.0.0+6fc22b9919
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.7.0+2122d82819
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.7.13+ba9dae0619
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.53+6ced4dd919
			fabric-item-api-v1: Fabric Item API (v1) 11.1.1+d5debaed19
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.1.6+6823f7cd19
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.47+0af3f5a719
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.45+df3654b319
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.5.0+01d9a51c19
			fabric-loot-api-v2: Fabric Loot API (v2) 3.0.15+3f89f5a519
			fabric-loot-api-v3: Fabric Loot API (v3) 1.0.3+3f89f5a519
			fabric-message-api-v1: Fabric Message API (v1) 6.0.13+6573ed8c19
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 2.0.0+fe474d6b19
			fabric-networking-api-v1: Fabric Networking API (v1) 4.3.0+c7469b2119
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 15.2.1+40875a9319
			fabric-particles-v1: Fabric Particles (v1) 4.0.2+6573ed8c19
			fabric-recipe-api-v1: Fabric Recipe API (v1) 5.0.13+6508971219
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 5.2.0+34f5d91419
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.4.0+c705a49c19
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.7.0+c705a49c19
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.68+df3654b319
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.48+73761d2e19
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.1.6+1daea21519
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.71+df3654b319
			fabric-rendering-v1: Fabric Rendering (v1) 5.0.5+df16efd019
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 4.3.0+8dc279b119
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 1.3.1+5b5275af19
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.25+8b68f1c719
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.88+b559734419
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.23+6573ed8c19
			fabric-transfer-api-v1: Fabric Transfer API (v1) 5.4.2+95bead5f19
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 6.2.0+45b9699719
		fabric-language-kotlin: Fabric Language Kotlin 1.12.3+kotlin.2.0.21
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 2.0.21
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 2.0.21
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 2.0.21
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 2.0.21
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.25.0
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.9.0
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.9.0
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.6.1
			org_jetbrains_kotlinx_kotlinx-io-bytestring-jvm: kotlinx-io-bytestring-jvm 0.5.4
			org_jetbrains_kotlinx_kotlinx-io-core-jvm: kotlinx-io-core-jvm 0.5.4
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.7.3
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.7.3
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.7.3
		fabricloader: Fabric Loader 0.16.9
			mixinextras: MixinExtras 0.4.1
		forcecloseworldloadingscreen: kennytv's epic force close loading screen mod for Fabric 2.2.2
		iris: Iris 1.8.1+mc1.21.1
			io_github_douira_glsl-transformer: glsl-transformer 2.0.1
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.13.1
		java: OpenJDK 64-Bit Server VM 21
		jei: Just Enough Items 19.21.0.247
		loadingscreentips: Loading Screen Tips 1.3.6
			midnightlib: MidnightLib 1.5.7
		malilib: MaLiLib 0.21.0
		minecraft: Minecraft 1.21.1
		modmenu: Mod Menu 11.0.3
			placeholder-api: Placeholder API 2.4.0-pre.2+1.21
		motionblur: Motion Blur 1.0.5+mc1.21
		notenoughcrashes: Not Enough Crashes 4.4.8+1.21
		reeses-sodium-options: Reese's Sodium Options 1.8.0+mc1.21.3
		replaymod: Replay Mod 1.21-2.6.19
		resourcify: Resourcify 1.5.0.1
		satin: Satin 2.0.0
		screenshotclipboard: Screenshot to Clipboard 1.0.10
		shulkerboxtooltip: Shulker Box Tooltip 5.1.2+1.21.1
		skinlayers3d: 3d-Skin-Layers 1.7.2
		skinshuffle: SkinShuffle 2.2.2+1.21
			com_konghq_unirest-java_standalone: unirest-java 3.11.9
			commons-validator_commons-validator: commons-validator 1.7
			org_jsoup_jsoup: jsoup 1.16.1
			org_mineskin_java-client: java-client 1.2.4-SNAPSHOT
			spruceui: SpruceUI 5.1.0+1.21
			yet_another_config_lib_v3: YetAnotherConfigLib 3.5.0+1.21-fabric
				com_twelvemonkeys_common_common-image: common-image 3.10.0
				com_twelvemonkeys_common_common-io: common-io 3.10.0
				com_twelvemonkeys_common_common-lang: common-lang 3.10.0
				com_twelvemonkeys_imageio_imageio-core: imageio-core 3.10.0
				com_twelvemonkeys_imageio_imageio-metadata: imageio-metadata 3.10.0
				com_twelvemonkeys_imageio_imageio-webp: imageio-webp 3.10.0
				org_quiltmc_parsers_gson: gson 0.2.1
				org_quiltmc_parsers_json: json 0.2.1
		sodium: Sodium 0.6.3+mc1.21.1
		sodium-extra: Sodium Extra 0.6.0+mc1.21.1
		stendhal: Stendhal 1.4.1-1.21
			libgui: LibGui 11.0.0+1.21
				jankson: Jankson 8.0.0+j1.2.3
					blue_endless_jankson: jankson 1.2.3
				libninepatch: LibNinePatch 1.2.0
		tcdcommons: TCD Commons API 3.12.4+fabric-1.21
		tooltipfix: ToolTip Fix 1.1.1-1.20
		tweakeroo: Tweakeroo 0.21.50
		wurst: Wurst Client v7.46.1-MC1.21.1
		xaerominimap: Xaero's Minimap 24.6.1
	Loaded Shaderpack: (off)
	Client Crashes Since Restart: 2
	Integrated Server Crashes Since Restart: 0
	Suspected Mods: Minecraft (minecraft), Fabric Loader (fabricloader), Not Enough Crashes (notenoughcrashes), Do a Barrel Roll (do_a_barrel_roll)

# Photo
![image](https://github.com/user-attachments/assets/52b74987-0e66-42d6-9833-476d17fa0910)

**Comment by r4ndombr0** [comment]
try deleting some mods, it helped me!
