### ISSUE TITLE
No config screen (1.19.2 both YACL and Cloth Config v8 are installed)

### ISSUE THREAD

**Issue by xlifi** [enjarai/do-a-barrel-roll#46]
<details>
  <summary>Error warning found in the logs</summary>
  
  
[22:05:35] [Render thread/ERROR]: Error from mod 'do_a_barrel_roll' java.lang.IncompatibleClassChangeError: Found class dev.isxander.yacl.api.YetAnotherConfigLib$Builder, but interface was expected 	at nl.enjarai.doabarrelroll.moonlightconfigs.yacl.YACLCompat.makeScreen(YACLCompat.java:34) ~[do-a-barrel-roll-2.4.0+1.19.2-fabric.jar:?] 	at nl.enjarai.doabarrelroll.moonlightconfigs.fabric.FabricConfigSpec.makeScreen(FabricConfigSpec.java:94) ~[do-a-barrel-roll-2.4.0+1.19.2-fabric.jar:?] 	at nl.enjarai.doabarrelroll.moonlightconfigs.ConfigSpec.makeScreen(ConfigSpec.java:93) ~[do-a-barrel-roll-2.4.0+1.19.2-fabric.jar:?] 	at com.terraformersmc.modmenu.ModMenu.getConfigScreen(ModMenu.java:54) ~[modmenu-4.1.2.jar:?] 	at com.terraformersmc.modmenu.gui.ModsScreen.method_25426(ModsScreen.java:117) ~[modmenu-4.1.2.jar:?] 	at net.minecraft.class_437.method_41843(class_437.java:389) ~[client-intermediary.jar:?] 	at net.minecraft.class_437.method_25423(class_437.java:380) ~[client-intermediary.jar:?] 	at net.minecraft.class_310.method_1507(class_310.java:1035) ~[client-intermediary.jar:?] 	at com.terraformersmc.modmenu.gui.widget.ModMenuButtonWidget.lambda$new$0(ModMenuButtonWidget.java:11) ~[modmenu-4.1.2.jar:?] 	at net.minecraft.class_4185.method_25306(class_4185.java:43) ~[client-intermediary.jar:?] 	at net.minecraft.class_4264.method_25348(class_4264.java:16) ~[client-intermediary.jar:?] 	at net.minecraft.class_339.method_25402(class_339.java:120) ~[client-intermediary.jar:?] 	at net.minecraft.class_4069.method_25402(class_4069.java:27) ~[client-intermediary.jar:?] 	at net.minecraft.class_442.method_25402(class_442.java:343) ~[client-intermediary.jar:?] 	at net.minecraft.class_312.method_1611(class_312.java:94) ~[client-intermediary.jar:?] 	at net.minecraft.class_437.method_25412(class_437.java:489) ~[client-intermediary.jar:?] 	at net.minecraft.class_312.method_1601(class_312.java:94) ~[client-intermediary.jar:?] 	at net.minecraft.class_312.method_22686(class_312.java:165) ~[client-intermediary.jar:?] 	at net.minecraft.class_1255.execute(class_1255.java:103) ~[client-intermediary.jar:?] 	at net.minecraft.class_312.method_22684(class_312.java:165) ~[client-intermediary.jar:?] 	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43) [lwjgl-glfw-3.3.1.jar:build 7] 	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.3.1.jar:build 7] 	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3474) [lwjgl-glfw-3.3.1.jar:build 7] 	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:222) [client-intermediary.jar:?] 	at net.minecraft.class_310.method_1523(class_310.java:1208) [client-intermediary.jar:?] 	at net.minecraft.class_310.method_1514(class_310.java:768) [client-intermediary.jar:?] 	at net.minecraft.client.main.Main.method_44604(Main.java:244) [client-intermediary.jar:?] 	at net.minecraft.client.main.Main.main(Main.java:51) [client-intermediary.jar:?] 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] 	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] 	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:423) [quilt-loader-0.17.8.jar:?] 	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:76) [quilt-loader-0.17.8.jar:?] 	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:24) [quilt-loader-0.17.8.jar:?] 	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88) [NewLaunch.jar:?] 	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126) [NewLaunch.jar:?] 	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71) [NewLaunch.jar:?]
 [22:05:35] [Render thread/INFO]: Mixing client.MixinChatOptionsScreen from nochatreports.mixins.json into net.minecraft.class_404
  [22:05:36] [Render thread/INFO]: CameraOverhaul: Using implementation #0 for abstraction 'CreateText'. 
  [22:05:36] [Render thread/INFO]: Generating YACL screen 
  [22:05:36] [Render thread/INFO]: Generating YACL screen
  </details>
  
![image](https://user-images.githubusercontent.com/70767436/210776785-8b0c24f4-42bf-4a3b-9977-f3f4660b9052.png)

  Ask if you need more information

**Comment by enjarai** [comment]
This is a known issue with the non-latest version of YACL that I'm not able to fix. Update YACL to version 2.1.1+.
