### ISSUE TITLE
Launch Failure "Mod do_a_barrel_roll provides a broken implementation of ModMenuApi"

### ISSUE THREAD

**Issue by Potato22** [enjarai/do-a-barrel-roll#74]
**Describe the issue**
Minecraft fails to launch with the mod enabled.

**Crash report/logs (if applicable)**
full: https://mclo.gs/LQsvTWL
highlight:
```
[04:11:37] [Render thread/ERROR]: Mod do_a_barrel_roll provides a broken implementation of ModMenuApi
--
1314 | java.lang.NoClassDefFoundError: dev/isxander/yacl/api/Controller
1315 | at nl.enjarai.doabarrelroll.compat.modmenu.ModMenuIntegration.getModConfigScreenFactory(ModMenuIntegration.java:11) ~[transformed-mod-do-a-barrel-roll.i0:0/:?]
1316 | at com.terraformersmc.modmenu.ModMenu.lambda$onInitializeClient$1(ModMenu.java:75) ~[transformed-mod-modmenu.i0:0/:?]
1317 | at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
1318 | at com.terraformersmc.modmenu.ModMenu.onInitializeClient(ModMenu.java:70) ~[transformed-mod-modmenu.i0:0/:?]
1319 | at org.quiltmc.loader.impl.game.minecraft.Hooks.lambda$startClient$1(Hooks.java:56) ~[quilt-loader-0.18.10.jar:?]
1320 | at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke$0(EntrypointUtils.java:36) ~[quilt-loader-0.18.10.jar:?]
1321 | at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:62) ~[quilt-loader-0.18.10.jar:?]
1322 | at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invokeContainer(EntrypointUtils.java:49) ~[quilt-loader-0.18.10.jar:?]
1323 | at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:36) ~[quilt-loader-0.18.10.jar:?]
1324 | at org.quiltmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:56) ~[quilt-loader-0.18.10.jar:?]
1325 | at net.minecraft.class_310.<init>(class_310.java:468) ~[transformed-mod-minecraft.i0:0/:?]
1326 | at net.minecraft.client.main.Main.main(Main.java:198) ~[minecraft-1.19.4-client.jar:?]
1327 | at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
1328 | at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
1329 | at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
1330 | at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
1331 | at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:527) ~[quilt-loader-0.18.10.jar:?]
1332 | at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:82) ~[quilt-loader-0.18.10.jar:?]
1333 | at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:28) ~[quilt-loader-0.18.10.jar:?]
1334 | at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88) ~[NewLaunch.jar:?]
1335 | at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126) ~[NewLaunch.jar:?]
1336 | at org.prismlauncher.EntryPoint.main(EntryPoint.java:71) ~[NewLaunch.jar:?]
1337 | Caused by: java.lang.ClassNotFoundException: dev.isxander.yacl.api.Controller
1338 | at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
1339 | at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188) ~[?:?]
1340 | at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
1341 | at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.loadClassOnly(KnotClassDelegate.java:178) ~[quilt-loader-0.18.10.jar:?]
1342 | at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:150) ~[quilt-loader-0.18.10.jar:?]
1343 | at org.quiltmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:228) ~[quilt-loader-0.18.10.jar:?]
1344 | at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
1345 | ... 22 more
```

**Additional information**
Put any additional info here. e.g. screenshots/videos, config files.
mod list:
![image](https://github.com/enjarai/do-a-barrel-roll/assets/39096741/953ed3dd-8d94-48d1-a898-a75975a629a8)

**Comment by enjarai** [comment]
Going a bit further down the log, you'll see the actual error. The one you highlight is related.

> Caused by: java.lang.IllegalStateException: Do a Barrel Roll requires Yet Another Config Lib (YACL) to be installed!
