### ISSUE TITLE
YACL dependency version too low

### ISSUE THREAD

**Issue by MC-XiaoHei** [enjarai/do-a-barrel-roll#79]
**Describe the issue**
Unable to start when installing both the latest release of this module and the latest release of YACL on 1.19.4

**Crash report/logs (if applicable)**
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'do_a_barrel_roll'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
	at net.minecraft.class_310.<init>(class_310.java:468)
	at net.minecraft.client.main.Main.main(Main.java:198)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:60)
	at oolloo.jlw.Wrapper.main(Wrapper.java:53)
Caused by: java.lang.NoClassDefFoundError: dev/isxander/yacl/api/Controller
	at nl.enjarai.doabarrelroll.DoABarrelRollClient.<clinit>(DoABarrelRollClient.java:27)
	at nl.enjarai.doabarrelroll.fabric.DoABarrelRollFabricClient.onInitializeClient(DoABarrelRollFabricClient.java:31)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 13 more
Caused by: java.lang.ClassNotFoundException: dev.isxander.yacl.api.Controller
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 16 more
**Additional information**
Based on my investigation, it was found that the package path of YACL 2 that this module relies on is "dev. isxander. yacl", but the package path of the latest version of YACL 3 is "dev. isxander. yacl3". Therefore, if both the latest release of this module and the latest release of YACL are installed, it will not be possible to start

**Comment by MenacingPerson** [comment]
It's not a bug. The mod will update on 1.20 release. In the meantime you can use yacl2 and yacl3 together, they will work

**Comment by MC-XiaoHei** [comment]
Okay, but I think you should at least point this out in README or Release
