### ISSUE TITLE
Barrel roll mod asking for a bad dependency Fabric

### ISSUE THREAD

**Issue by JuanJoseAriasJaramillo** [enjarai/do-a-barrel-roll#83]
**Describe the issue**
version 1.20
The mod was working completely fine, then i update both, the mod and the depency, to the last available version in curse forge.

**Crash report/logs (if applicable)**
Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Install yet_another_config_lib_v3, any 3.x version.
Unmet dependency listing:
	 - Mod 'Do a Barrel Roll' (do_a_barrel_roll) 3.0.0-beta.2+1.20 requires any 3.x version of yet_another_config_lib_v3, which is missing!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:192)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Additional information**
Put any additional info here. e.g. screenshots/videos, config files.

**Comment by enjarai** [comment]
`yet_another_config_lib_v3` is a valid dependency, it just wasn't required on some older versions. Make sure to install this specific version or newer: https://www.curseforge.com/minecraft/mc-mods/yacl/files/4574163
